include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    public_member_api_docs: ignore
    cascade_invocations: ignore
    avoid_positional_boolean_parameters: ignore
    document_ignores: ignore
    avoid_catches_without_on_clauses: ignore
