name: soundnexus
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  audioplayers: ^6.1.0
  cupertino_icons: ^1.0.8
  desktop_drop: ^0.5.0
  flex_seed_scheme: ^3.4.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.3
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  get_it: ^8.0.3
  get_storage: ^2.1.1
  go_router: ^14.3.0
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.5.3
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
