name: soundnexus
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  audioplayers: ^6.1.0
  collection: ^1.19.0
  context_watch: ^7.0.2
  cupertino_icons: ^1.0.8
  desktop_drop: ^0.6.1
  flex_seed_scheme: ^3.4.1
  flutter:
    sdk: flutter
  freezed: ^3.2.0
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  get_it: ^8.0.3
  get_storage: ^2.1.1
  go_router: ^16.2.1
  json_annotation: ^4.9.0
  json_serializable: ^6.9.3
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
